import type { Product } from "@/types/product";
import type { StockMovement } from "@/types/stock";
import type { Supplier } from "@/types/supplier";

export const dashboardStats = [
  { label: "Total products", value: "1,284", delta: "+12 this week" },
  { label: "Inventory value", value: "PHP 2.8M", delta: "+6.4% month over month" },
  { label: "Low stock", value: "32", delta: "Needs reorder" },
  { label: "Out of stock", value: "7", delta: "Urgent review" },
];

export const categories = [
  "Electronics",
  "Office Supplies",
  "Packaging",
  "Maintenance",
  "Raw Materials",
];

export const products: Product[] = [
  {
    id: "PRD-001",
    name: "Barcode Scanner X200",
    sku: "BSC-X200",
    category: "Electronics",
    supplier: "Northline Supply",
    quantity: 42,
    reorderLevel: 15,
    price: 5800,
    status: "In Stock",
    location: "Aisle A1",
  },
  {
    id: "PRD-002",
    name: "Thermal Label Roll",
    sku: "LBL-4X6",
    category: "Packaging",
    supplier: "Prime Pack Co.",
    quantity: 12,
    reorderLevel: 20,
    price: 420,
    status: "Low Stock",
    location: "Aisle B3",
  },
  {
    id: "PRD-003",
    name: "Industrial Gloves",
    sku: "SAFE-GLV",
    category: "Maintenance",
    supplier: "Metro Safety",
    quantity: 0,
    reorderLevel: 30,
    price: 185,
    status: "Out of Stock",
    location: "Aisle C2",
  },
  {
    id: "PRD-004",
    name: "Printer Ink Cartridge",
    sku: "INK-BLK-90",
    category: "Office Supplies",
    supplier: "Office Hub",
    quantity: 68,
    reorderLevel: 18,
    price: 960,
    status: "In Stock",
    location: "Aisle D1",
  },
  {
    id: "PRD-005",
    name: "Aluminum Sheet 2mm",
    sku: "RAW-ALU-2",
    category: "Raw Materials",
    supplier: "AlloyWorks",
    quantity: 19,
    reorderLevel: 25,
    price: 1480,
    status: "Low Stock",
    location: "Bay R4",
  },
];

export const stockMovements: StockMovement[] = [
  {
    id: "MOV-1048",
    product: "Thermal Label Roll",
    sku: "LBL-4X6",
    type: "Stock Out",
    quantity: 24,
    actor: "Mika Reyes",
    date: "Today, 10:42 AM",
    note: "Released for shipping team",
  },
  {
    id: "MOV-1047",
    product: "Barcode Scanner X200",
    sku: "BSC-X200",
    type: "Stock In",
    quantity: 18,
    actor: "Jon Dela Cruz",
    date: "Today, 9:18 AM",
    note: "Received from supplier",
  },
  {
    id: "MOV-1046",
    product: "Aluminum Sheet 2mm",
    sku: "RAW-ALU-2",
    type: "Adjustment",
    quantity: 4,
    actor: "Ana Santos",
    date: "Yesterday, 5:06 PM",
    note: "Cycle count correction",
  },
  {
    id: "MOV-1045",
    product: "Industrial Gloves",
    sku: "SAFE-GLV",
    type: "Stock Out",
    quantity: 35,
    actor: "Liam Tan",
    date: "Yesterday, 2:30 PM",
    note: "Maintenance request",
  },
];

export const suppliers: Supplier[] = [
  {
    id: "SUP-001",
    name: "Northline Supply",
    contact: "Ramon Lee",
    email: "orders@northline.example",
    phone: "+63 917 100 4200",
    products: 18,
    leadTime: "3-5 days",
    status: "Active",
  },
  {
    id: "SUP-002",
    name: "Prime Pack Co.",
    contact: "Grace Lim",
    email: "sales@primepack.example",
    phone: "+63 918 441 1120",
    products: 24,
    leadTime: "2-4 days",
    status: "Review",
  },
  {
    id: "SUP-003",
    name: "Metro Safety",
    contact: "Paolo Garcia",
    email: "support@metrosafety.example",
    phone: "+63 919 220 7781",
    products: 12,
    leadTime: "5-7 days",
    status: "Paused",
  },
  {
    id: "SUP-004",
    name: "Office Hub",
    contact: "Leah Cruz",
    email: "hello@officehub.example",
    phone: "+63 917 875 6021",
    products: 31,
    leadTime: "1-3 days",
    status: "Active",
  },
];
